// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcjMOA3oV1I1KM7SXQrScBKfvOtqZuMd0',
    appId: '1:1043798375951:android:5c2773046333f1d9c2ad7a',
    messagingSenderId: '1043798375951',
    projectId: 'dog-hub-c7908',
    storageBucket: 'dog-hub-c7908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD09HmvNclFIC3MAxlJ7M7TwZm8-nczl08',
    appId: '1:1043798375951:ios:f4e642067f2f8879c2ad7a',
    messagingSenderId: '1043798375951',
    projectId: 'dog-hub-c7908',
    storageBucket: 'dog-hub-c7908.appspot.com',
    androidClientId: '1043798375951-64no4dvuv68v7i779fommgpgu4tvdm6p.apps.googleusercontent.com',
    iosClientId: '1043798375951-v1a8npb0a05gkjhgjvhhbr474ip4eh00.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
